### ISSUE TITLE
Doesn't run on Win10X64

### ISSUE THREAD

**Issue by rafaelvasco** [lithiumtoast/sokol-csharp#1]
Examples fail to run on Win10x64: Could not find sokol_gfx library. The library (sokol windows opengl release) is right there so maybe there's a problem in the DLL itself ?

**Comment by lithiumtoast** [comment]
Hello, thanks for feedback! 

Are you using the `master` branch?

**Comment by rafaelvasco** [comment]
Ah yeah. That could be it. I'll give it a try later today and report back. Thanks!

**Comment by lithiumtoast** [comment]
Hmm, no. I meant that `develop` is what I have tested right now. I'll take a look into this later today.

**Comment by rafaelvasco** [comment]
Yeah I'm in master right now. Is it working in develop ? If yes I'll give it a try using develop later.

**Comment by lithiumtoast** [comment]
Found an issue. Working on a fix. In the meantime, if you want to see a sample working you can checkout commit `07084f8a264a1d5c8edc890d13a973d1b326af82`.

**Comment by rafaelvasco** [comment]
No luck with develop as well. The exact error is:
"System.DllNotFoundException: 'Unable to load DLL 'sokol_gfx' or one of its dependencies". Sadly I had compiled sokol before but threw it away and now I can't compile it again lol.

**Comment by rafaelvasco** [comment]
Great. Thanks. And forgot to say, thanks for your work!

**Comment by lithiumtoast** [comment]
I fixed the problem in `develop`. I tested it on my Windows 10 x64 machine. If you have a chance could you also see if `develop` works for you now?

**Comment by rafaelvasco** [comment]
Ok , i'll give it a try later today. Thanks!

**Comment by rafaelvasco** [comment]
Great, it runs perfectly now! Thanks!
